# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_crypto_V3.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1079, 866)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(True)
        self.windows_layout = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.windows_layout.sizePolicy().hasHeightForWidth())
        self.windows_layout.setSizePolicy(sizePolicy)
        self.windows_layout.setStyleSheet("/*-----QWidget-----*/\n"
"QWidget\n"
"{\n"
"    background-color: #121212;\n"
"    color: #ffffff;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLabel-----*/\n"
"QLabel\n"
"{\n"
"    background-color: transparent;\n"
"    color: #ffffff;\n"
"\n"
"}\n"
"\n"
"\n"
"QLabel::disabled\n"
"{\n"
"    background-color: transparent;\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QMenuBar-----*/\n"
"QMenuBar\n"
"{\n"
"    background-color: #0a0a0a;\n"
"    color: #ffffff;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item\n"
"{\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item:selected\n"
"{\n"
"    background-color: #607cff;\n"
"    border: 1px solid #41cd52;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item:pressed\n"
"{\n"
"    background-color: #4969ff;\n"
"    border: 1px solid #000;\n"
"    margin-bottom: -1px;\n"
"    padding-bottom: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QMenu-----*/\n"
"QMenu\n"
"{\n"
"    background-color: #121212;\n"
"    border: 1px solid;\n"
"    color: #ffffff;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::separator\n"
"{\n"
"    height: 1px;\n"
"    background-color: #6d8eff;\n"
"    color: #ffffff;\n"
"    padding-left: 4px;\n"
"    margin-left: 10px;\n"
"    margin-right: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item\n"
"{\n"
"    min-width : 150px;\n"
"    padding: 3px 20px 3px 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"    background-color: #4969ff;\n"
"    color: #ffffff;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item:disabled\n"
"{\n"
"    color: #262626;\n"
"}\n"
"\n"
"\n"
"/*-----QToolTip-----*/\n"
"QToolTip\n"
"{\n"
"    border : 1px solid #000000;\n"
"    background-color: #26264f;\n"
"    color: #ffffff;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"/*-----QPushButton-----*/\n"
"QPushButton\n"
"{\n"
"    background-color: #607cff;\n"
"    color: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    border-color: #051a39;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #8399ff;\n"
"    color: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    border-color: #051a39;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #4969ff;\n"
"    color: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    border-color: #051a39;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolButton-----*/\n"
"QToolButton\n"
"{\n"
"    background-color: #607cff;\n"
"    color: #ffffff;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    border-color: #051a39;\n"
"    padding: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolButton::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolButton::hover\n"
"{\n"
"    background-color: #8399ff;\n"
"    color: #ffffff;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    border-color: #051a39;\n"
"    padding: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolButton::pressed\n"
"{\n"
"    background-color: #4969ff;\n"
"    color: #ffffff;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    border-color: #051a39;\n"
"    padding: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QComboBox-----*/\n"
"QComboBox\n"
"{\n"
"    background-color: #607cff;\n"
"    border: 1px solid;\n"
"    border-radius: 3px;\n"
"    padding-left: 6px;\n"
"    color: #ffffff;\n"
"    height: 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox:hover\n"
"{\n"
"    background-color: #8399ff;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox:on\n"
"{\n"
"    background-color: #4969ff;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    background-color: #383838;\n"
"    color: #ffffff;\n"
"    border: 1px solid black;\n"
"    selection-background-color: #4969ff;\n"
"    selection-color: #ffffff;\n"
"    outline: 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox::drop-down\n"
"{\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    border-left-width: 0px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; \n"
"    border-top-right-radius: 3px; \n"
"    border-bottom-right-radius: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox::down-arrow\n"
"{\n"
"    image: url(://arrow-down.png);\n"
"    width: 8px;\n"
"    height: 8px;\n"
"}\n"
"\n"
"\n"
"/*-----QSpinBox & QDoubleSpinBox & QDateTimeEdit-----*/\n"
"QSpinBox, \n"
"QDoubleSpinBox,\n"
"QDateTimeEdit\n"
"{\n"
"    background-color: #525251;\n"
"    color: #ffffff;\n"
"    border: 1px solid #051a39;\n"
"    border-radius: 3px;\n"
"    padding : 2px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::disabled, \n"
"QDoubleSpinBox::disabled,\n"
"QDateTimeEdit::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox:hover, \n"
"QDoubleSpinBox::hover,\n"
"QDateTimeEdit::hover\n"
"{\n"
"    background-color: #626262;\n"
"    border: 1px solid #607cff;\n"
"    color:  #fff;\n"
"    padding: 2px\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-button, QSpinBox::down-button,\n"
"QDoubleSpinBox::up-button, QDoubleSpinBox::down-button,\n"
"QDateTimeEdit::up-button, QDateTimeEdit::down-button\n"
"{\n"
"    background-color: #607cff;\n"
"    border-radius: 2px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::disabled, \n"
"QDoubleSpinBox::disabled,\n"
"QDateTimeEdit::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-button:hover, QSpinBox::down-button:hover,\n"
"QDoubleSpinBox::up-button:hover, QDoubleSpinBox::down-button:hover,\n"
"QDateTimeEdit::up-button:hover, QDateTimeEdit::down-button:hover\n"
"{\n"
"    background-color: #8399ff;\n"
"    border: 1px solid #8399ff;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-button:disabled, QSpinBox::down-button:disabled,\n"
"QDoubleSpinBox::up-button:disabled, QDoubleSpinBox::down-button:disabled,\n"
"QDateTimeEdit::up-button:disabled, QDateTimeEdit::down-button:disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-button:pressed, QSpinBox::down-button:pressed,\n"
"QDoubleSpinBox::up-button:pressed, QDoubleSpinBox::down-button::pressed,\n"
"QDateTimeEdit::up-button:pressed, QDateTimeEdit::down-button::pressed\n"
"{\n"
"    background-color: #4969ff;\n"
"    border: 1px solid #4969ff;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::down-arrow,\n"
"QDoubleSpinBox::down-arrow,\n"
"QDateTimeEdit::down-arrow\n"
"{\n"
"    image: url(://arrow-down.png);\n"
"    width: 7px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-arrow,\n"
"QDoubleSpinBox::up-arrow,\n"
"QDateTimeEdit::up-arrow\n"
"{\n"
"    image: url(://arrow-up.png);\n"
"    width: 7px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLineEdit-----*/\n"
"QLineEdit\n"
"{\n"
"    background-color: #525251;\n"
"    color: #ffffff;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    border-color: #051a39;\n"
"    padding: 2px;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    border-color: #051a39;\n"
"    padding: 2px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QTextEdit-----*/\n"
"QTextEdit\n"
"{\n"
"    /* background-color: rgb(18, 18, 18); */\n"
"    color: #cecece;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QTextEdit::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QGroupBox-----*/\n"
"QGroupBox \n"
"{\n"
"    border: 1px solid;\n"
"    border-color: #607cff;\n"
"    margin-top: 22px;\n"
"\n"
"}\n"
"\n"
"\n"
"QGroupBox::title  \n"
"{\n"
"    background-color: #607cff;\n"
"    color: #ffffff;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 5px;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QGroupBox::title::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 5px;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QRadioButton-----*/\n"
"QRadioButton::indicator::unchecked\n"
"{ \n"
"    border: 2px inset gray; \n"
"    border-radius: 5px; \n"
"    background-color:  #fff;\n"
"    width: 9px; \n"
"    height: 9px; \n"
"\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::unchecked:hover\n"
"{ \n"
"    border: 2px solid #607cff; \n"
"    border-radius: 5px; \n"
"    background-color:  #fff;\n"
"    width: 9px; \n"
"    height: 9px; \n"
"\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::checked\n"
"{ \n"
"    border: 2px inset darkgray; \n"
"    border-radius: 5px; \n"
"    background-color: #4969ff; \n"
"    width: 9px; \n"
"    height: 9px; \n"
"\n"
"}\n"
"\n"
"\n"
"QRadioButton::disabled\n"
"{\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator:disabled\n"
"{\n"
"    background-color: #656565;\n"
"    color: #656565;\n"
"    border: 2px solid #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QTableView & QTableWidget-----*/\n"
"QTableView\n"
"{\n"
"    background-color: #242526;\n"
"    border: 1px solid #32414B;\n"
"    color: #f0f0f0;\n"
"    gridline-color: #8faaff;\n"
"    outline : 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableView::disabled\n"
"{\n"
"    background-color: #242526;\n"
"    border: 1px solid #32414B;\n"
"    color: #656565;\n"
"    gridline-color: #656565;\n"
"    outline : 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableView::item:hover \n"
"{\n"
"    background-color: #26264f;\n"
"    color: #f0f0f0;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableView::item:selected \n"
"{\n"
"    background-color: #1a1b1c;\n"
"    border: 2px solid #4969ff;\n"
"    color: #F0F0F0;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableView::item:selected:disabled\n"
"{\n"
"    background-color: #1a1b1c;\n"
"    border: 2px solid #525251;\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableCornerButton::section\n"
"{\n"
"    background-color: #505050;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section\n"
"{\n"
"    background-color: #525251;\n"
"    color: #fff;\n"
"    text-align: left;\n"
"    padding: 4px;\n"
"    \n"
"}\n"
"\n"
"\n"
"QHeaderView::section:disabled\n"
"{\n"
"    background-color: #525251;\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section:checked\n"
"{\n"
"    color: #fff;\n"
"    background-color: #4969ff;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section:checked:disabled\n"
"{\n"
"    color: #656565;\n"
"    background-color: #525251;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::vertical::first,\n"
"QHeaderView::section::vertical::only-one\n"
"{\n"
"    border-top: 1px solid #353635;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::vertical\n"
"{\n"
"    border-top: 1px solid #353635;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::horizontal::first,\n"
"QHeaderView::section::horizontal::only-one\n"
"{\n"
"    border-left: 1px solid #353635;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::horizontal\n"
"{\n"
"    border-left: 1px solid #353635;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QTabWidget-----*/\n"
"QTabBar::tab\n"
"{\n"
"    background-color: #262626;\n"
"    color: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    border-color: #051a39;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:disabled\n"
"{\n"
"    background-color: #656565;\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabWidget::pane \n"
"{\n"
"    background-color: #262626;\n"
"    color: #ffffff;\n"
"    border: 1px solid;\n"
"    border-color: #607cff;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:selected\n"
"{\n"
"    background-color: #607cff;\n"
"    color: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    border-color: #051a39;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:selected:disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:!selected \n"
"{\n"
"    background-color: #262626;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:!selected:hover \n"
"{\n"
"    background-color: #8399ff;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:top:!selected \n"
"{\n"
"    margin-top: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:bottom:!selected \n"
"{\n"
"    margin-bottom: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:top, QTabBar::tab:bottom \n"
"{\n"
"    min-width: 8ex;\n"
"    margin-right: -1px;\n"
"    padding: 5px 10px 5px 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:top:selected \n"
"{\n"
"    border-bottom-color: none;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:bottom:selected \n"
"{\n"
"    border-top-color: none;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:top:last, QTabBar::tab:bottom:last,\n"
"QTabBar::tab:top:only-one, QTabBar::tab:bottom:only-one \n"
"{\n"
"    margin-right: 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:left:!selected \n"
"{\n"
"    margin-right: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:right:!selected\n"
"{\n"
"    margin-left: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:left, QTabBar::tab:right \n"
"{\n"
"    min-height: 8ex;\n"
"    margin-bottom: -1px;\n"
"    padding: 10px 5px 10px 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:left:selected \n"
"{\n"
"    border-left-color: none;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:right:selected \n"
"{\n"
"    border-right-color: none;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:left:last, QTabBar::tab:right:last,\n"
"QTabBar::tab:left:only-one, QTabBar::tab:right:only-one \n"
"{\n"
"    margin-bottom: 0;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QSlider-----*/\n"
"QSlider::groove:horizontal \n"
"{\n"
"    background-color: transparent;\n"
"    height: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:horizontal \n"
"{\n"
"    background-color: #607cff;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::add-page:horizontal \n"
"{\n"
"    background-color: #666765;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:horizontal \n"
"{\n"
"    background-color: #607cff;\n"
"    width: 14px;\n"
"    margin-top: -6px;\n"
"    margin-bottom: -6px;\n"
"    border-radius: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:horizontal:hover \n"
"{\n"
"    background-color: #607cff;\n"
"    border-radius: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:horizontal:disabled \n"
"{\n"
"    background-color: #bbb;\n"
"    border-color: #999;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::add-page:horizontal:disabled \n"
"{\n"
"    background-color: #eee;\n"
"    border-color: #999;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:horizontal:disabled \n"
"{\n"
"    background-color: #eee;\n"
"    border: 1px solid #aaa;\n"
"    border-radius: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::groove:vertical \n"
"{\n"
"    background-color: transparent;\n"
"    width: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:vertical \n"
"{\n"
"    background-color: #607cff;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::add-page:vertical \n"
"{\n"
"    background-color: #666765;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:vertical \n"
"{\n"
"    background-color: #607cff;\n"
"    height: 14px;\n"
"    margin-left: -6px;\n"
"    margin-right: -6px;\n"
"    border-radius: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:vertical:hover \n"
"{\n"
"    background-color: #607cff;\n"
"    border-radius: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:vertical:disabled \n"
"{\n"
"    background-color: #bbb;\n"
"    border-color: #999;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::add-page:vertical:disabled \n"
"{\n"
"    background-color: #eee;\n"
"    border-color: #999;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:vertical:disabled \n"
"{\n"
"    background-color: #eee;\n"
"    border: 1px solid #aaa;\n"
"    border-radius: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QDial-----*/\n"
"QDial\n"
"{\n"
"    background-color: #607cff;\n"
"\n"
"}\n"
"\n"
"\n"
"QDial::disabled\n"
"{\n"
"    background-color: #404040;\n"
"\n"
"}\n"
"\n"
"/*-----QScrollBar-----*/\n"
"QScrollBar:horizontal\n"
"{\n"
"    border: 1px solid #222222;\n"
"    background-color: #3d3d3d;\n"
"    height: 13px;\n"
"    margin: 0px 16px 0 16px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:horizontal\n"
"{\n"
"    background: #607cff;\n"
"    min-height: 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal\n"
"{\n"
"    border: 1px solid #1b1b19;\n"
"    background-color: #607cff;\n"
"    width: 14px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:horizontal\n"
"{\n"
"    border: 1px solid #1b1b19;\n"
"    background-color: #607cff;\n"
"    width: 14px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::right-arrow:horizontal\n"
"{\n"
"    image: url(://arrow-right.png);\n"
"    width: 6px;\n"
"    height: 6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::left-arrow:horizontal\n"
"{\n"
"    image: url(://arrow-left.png);\n"
"    width: 6px;\n"
"    height: 6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"    background: none;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"    background-color: #3d3d3d;\n"
"    width: 13px;\n"
"    margin: 16px 0 16px 0;\n"
"    border: 1px solid #222222;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
"    background-color: #607cff;\n"
"    min-height: 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"    border: 1px solid #1b1b19;\n"
"    background-color: #607cff;\n"
"    height: 14px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"    border: 1px solid #1b1b19;\n"
"    background-color: #607cff;\n"
"    height: 14px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::up-arrow:vertical\n"
"{\n"
"    image: url(://arrow-up.png);\n"
"    width: 6px;\n"
"    height: 6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::down-arrow:vertical\n"
"{\n"
"    image: url(://arrow-down.png);\n"
"    width: 6px;\n"
"    height: 6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"    background: none;\n"
"\n"
"}\n"
"\n"
"/*-----QProgressBar-----*/\n"
"QProgressBar\n"
"{\n"
"    border: 1px solid #222222;\n"
"    background-color: #3d3d3d;\n"
"    text-align: center;\n"
"    color: #ffffff;\n"
"    font-size: 12px;\n"
"    /* font-weight: bold; */\n"
"    padding: 1px;\n"
"    border-radius: 3px;\n"
"}\n"
"QProgressBar::chunk\n"
"{\n"
"    background-color: #607cff;\n"
"}")
        self.windows_layout.setObjectName("windows_layout")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.windows_layout)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.main_layout = QtWidgets.QGridLayout()
        self.main_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.main_layout.setContentsMargins(-1, -1, 0, 0)
        self.main_layout.setObjectName("main_layout")
        self.line_3 = QtWidgets.QFrame(self.windows_layout)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.main_layout.addWidget(self.line_3, 2, 1, 1, 1)
        self.tab_layout = QtWidgets.QGridLayout()
        self.tab_layout.setObjectName("tab_layout")
        self.tabtool_encoding = QtWidgets.QTabWidget(self.windows_layout)
        self.tabtool_encoding.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabtool_encoding.setMouseTracking(False)
        self.tabtool_encoding.setTabletTracking(False)
        self.tabtool_encoding.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabtool_encoding.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabtool_encoding.setIconSize(QtCore.QSize(20, 20))
        self.tabtool_encoding.setElideMode(QtCore.Qt.ElideNone)
        self.tabtool_encoding.setTabBarAutoHide(False)
        self.tabtool_encoding.setObjectName("tabtool_encoding")
        self.tab_normal = QtWidgets.QWidget()
        self.tab_normal.setObjectName("tab_normal")
        self.textEdit_port = QtWidgets.QTextEdit(self.tab_normal)
        self.textEdit_port.setGeometry(QtCore.QRect(20, 60, 81, 31))
        self.textEdit_port.setObjectName("textEdit_port")
        self.label_7 = QtWidgets.QLabel(self.tab_normal)
        self.label_7.setGeometry(QtCore.QRect(0, 10, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_7.setFont(font)
        self.label_7.setScaledContents(True)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.pushButton_port = QtWidgets.QPushButton(self.tab_normal)
        self.pushButton_port.setGeometry(QtCore.QRect(120, 60, 75, 23))
        self.pushButton_port.setObjectName("pushButton_port")
        self.plainTextEdit_normal = QtWidgets.QPlainTextEdit(self.tab_normal)
        self.plainTextEdit_normal.setGeometry(QtCore.QRect(10, 680, 389, 81))
        self.plainTextEdit_normal.setObjectName("plainTextEdit_normal")
        self.pushButton_normal = QtWidgets.QPushButton(self.tab_normal)
        self.pushButton_normal.setGeometry(QtCore.QRect(420, 730, 91, 31))
        self.pushButton_normal.setObjectName("pushButton_normal")
        self.tabtool_encoding.addTab(self.tab_normal, "")
        self.tab_shift = QtWidgets.QWidget()
        self.tab_shift.setObjectName("tab_shift")
        self.plainTextEdit_shift = QtWidgets.QPlainTextEdit(self.tab_shift)
        self.plainTextEdit_shift.setGeometry(QtCore.QRect(10, 678, 389, 81))
        self.plainTextEdit_shift.setObjectName("plainTextEdit_shift")
        self.pushButton_shift = QtWidgets.QPushButton(self.tab_shift)
        self.pushButton_shift.setGeometry(QtCore.QRect(420, 730, 91, 31))
        self.pushButton_shift.setObjectName("pushButton_shift")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.tab_shift)
        self.lcdNumber_3.setGeometry(QtCore.QRect(250, 200, 211, 181))
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.plainTextEdit_shift_key = QtWidgets.QPlainTextEdit(self.tab_shift)
        self.plainTextEdit_shift_key.setGeometry(QtCore.QRect(20, 340, 71, 31))
        self.plainTextEdit_shift_key.setObjectName("plainTextEdit_shift_key")
        self.pushButton_shift_key = QtWidgets.QPushButton(self.tab_shift)
        self.pushButton_shift_key.setGeometry(QtCore.QRect(110, 340, 91, 31))
        self.pushButton_shift_key.setObjectName("pushButton_shift_key")
        self.label_8 = QtWidgets.QLabel(self.tab_shift)
        self.label_8.setGeometry(QtCore.QRect(140, 20, 231, 121))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_8.setFont(font)
        self.label_8.setScaledContents(True)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.pushButton_clear = QtWidgets.QPushButton(self.tab_shift)
        self.pushButton_clear.setGeometry(QtCore.QRect(440, 10, 91, 31))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.tabtool_encoding.addTab(self.tab_shift, "")
        self.tab_vigenere = QtWidgets.QWidget()
        self.tab_vigenere.setObjectName("tab_vigenere")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_vigenere)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.buttonBox_key_vigenere = QtWidgets.QDialogButtonBox(self.tab_vigenere)
        self.buttonBox_key_vigenere.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_key_vigenere.setObjectName("buttonBox_key_vigenere")
        self.gridLayout_8.addWidget(self.buttonBox_key_vigenere, 7, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_vigenere)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_8.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_vigenere)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_5.setFont(font)
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_8.addWidget(self.label_5, 0, 1, 1, 1)
        self.buttonBoxSend_vigenere = QtWidgets.QDialogButtonBox(self.tab_vigenere)
        self.buttonBoxSend_vigenere.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBoxSend_vigenere.setObjectName("buttonBoxSend_vigenere")
        self.gridLayout_8.addWidget(self.buttonBoxSend_vigenere, 10, 1, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.tab_vigenere)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_8.addWidget(self.line_5, 9, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.tab_vigenere)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_8.addWidget(self.line_6, 9, 1, 1, 1)
        self.textBrowser_key_vigenere = QtWidgets.QTextBrowser(self.tab_vigenere)
        self.textBrowser_key_vigenere.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textBrowser_key_vigenere.setObjectName("textBrowser_key_vigenere")
        self.gridLayout_8.addWidget(self.textBrowser_key_vigenere, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem, 8, 0, 1, 1)
        self.plainTextEdit_vigenere = QtWidgets.QPlainTextEdit(self.tab_vigenere)
        self.plainTextEdit_vigenere.setObjectName("plainTextEdit_vigenere")
        self.gridLayout_8.addWidget(self.plainTextEdit_vigenere, 10, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem1, 0, 0, 1, 1)
        self.plainTextEdit_key_vigenere = QtWidgets.QPlainTextEdit(self.tab_vigenere)
        self.plainTextEdit_key_vigenere.setObjectName("plainTextEdit_key_vigenere")
        self.gridLayout_8.addWidget(self.plainTextEdit_key_vigenere, 7, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.tabtool_encoding.addTab(self.tab_vigenere, "")
        self.tab_rsa = QtWidgets.QWidget()
        self.tab_rsa.setObjectName("tab_rsa")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_rsa)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.PrivateKeyLabel = QtWidgets.QLabel(self.tab_rsa)
        self.PrivateKeyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.PrivateKeyLabel.setObjectName("PrivateKeyLabel")
        self.gridLayout_10.addWidget(self.PrivateKeyLabel, 5, 0, 1, 1)
        self.buttonBoxSend_RSA = QtWidgets.QDialogButtonBox(self.tab_rsa)
        self.buttonBoxSend_RSA.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBoxSend_RSA.setObjectName("buttonBoxSend_RSA")
        self.gridLayout_10.addWidget(self.buttonBoxSend_RSA, 8, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.tab_rsa)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_10.addWidget(self.line, 7, 0, 1, 1)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.tab_rsa)
        self.lcdNumber_2.setDigitCount(5)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.gridLayout_10.addWidget(self.lcdNumber_2, 4, 1, 1, 1)
        self.RSA_Key_button_generator = QtWidgets.QPushButton(self.tab_rsa)
        self.RSA_Key_button_generator.setObjectName("RSA_Key_button_generator")
        self.gridLayout_10.addWidget(self.RSA_Key_button_generator, 6, 1, 1, 1)
        self.PublicKeyLabel = QtWidgets.QLabel(self.tab_rsa)
        self.PublicKeyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.PublicKeyLabel.setObjectName("PublicKeyLabel")
        self.gridLayout_10.addWidget(self.PublicKeyLabel, 4, 0, 1, 1)
        self.plainTextEdit_RSA = QtWidgets.QPlainTextEdit(self.tab_rsa)
        self.plainTextEdit_RSA.setObjectName("plainTextEdit_RSA")
        self.gridLayout_10.addWidget(self.plainTextEdit_RSA, 8, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.tab_rsa)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_10.addWidget(self.line_4, 7, 1, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.tab_rsa)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout_10.addWidget(self.lcdNumber, 5, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem2, 6, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_rsa)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_4.setFont(font)
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_10.addWidget(self.label_4, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem3, 0, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_10, 2, 0, 1, 1)
        self.tabtool_encoding.addTab(self.tab_rsa, "")
        self.tab_DH = QtWidgets.QWidget()
        self.tab_DH.setObjectName("tab_DH")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_DH)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.buttonBox_5 = QtWidgets.QDialogButtonBox(self.tab_DH)
        self.buttonBox_5.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_5.setObjectName("buttonBox_5")
        self.gridLayout_12.addWidget(self.buttonBox_5, 11, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_DH)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_12.addWidget(self.pushButton_5, 4, 0, 1, 2)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_DH)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_12.addWidget(self.pushButton_4, 2, 0, 1, 2)
        self.line_10 = QtWidgets.QFrame(self.tab_DH)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_12.addWidget(self.line_10, 10, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem4, 7, 0, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.tab_DH)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_12.addWidget(self.line_9, 10, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_DH)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_12.addWidget(self.pushButton_9, 6, 0, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem5, 9, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_DH)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_12.addWidget(self.pushButton_3, 3, 0, 1, 2)
        self.chatTask = QtWidgets.QTextBrowser(self.tab_DH)
        self.chatTask.setObjectName("chatTask")
        self.gridLayout_12.addWidget(self.chatTask, 7, 1, 2, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_DH)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_12.addWidget(self.pushButton_8, 5, 0, 1, 2)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_DH)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_12.addWidget(self.pushButton_6, 1, 0, 1, 2)
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_DH)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_12.addWidget(self.pushButton_7, 0, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout_12, 0, 0, 2, 2)
        self.tabtool_encoding.addTab(self.tab_DH, "")
        self.tab_layout.addWidget(self.tabtool_encoding, 0, 0, 1, 1)
        self.main_layout.addLayout(self.tab_layout, 2, 0, 1, 1)
        self.chat_layout = QtWidgets.QVBoxLayout()
        self.chat_layout.setObjectName("chat_layout")
        self.label = QtWidgets.QLabel(self.windows_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.chat_layout.addWidget(self.label)
        self.line_2 = QtWidgets.QFrame(self.windows_layout)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.chat_layout.addWidget(self.line_2)
        self.ChatDisplay = QtWidgets.QTextBrowser(self.windows_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ChatDisplay.sizePolicy().hasHeightForWidth())
        self.ChatDisplay.setSizePolicy(sizePolicy)
        self.ChatDisplay.setMinimumSize(QtCore.QSize(0, 0))
        self.ChatDisplay.setObjectName("ChatDisplay")
        self.chat_layout.addWidget(self.ChatDisplay)
        self.main_layout.addLayout(self.chat_layout, 0, 2, 3, 1)
        self.gridLayout_7.addLayout(self.main_layout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.windows_layout)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1079, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabtool_encoding.setCurrentIndex(0)
        self.buttonBoxSend_RSA.accepted.connect(self.plainTextEdit_RSA.clear) # type: ignore
        self.buttonBoxSend_RSA.rejected.connect(self.plainTextEdit_RSA.clear) # type: ignore
        self.buttonBox_key_vigenere.accepted.connect(self.plainTextEdit_key_vigenere.clear) # type: ignore
        self.buttonBox_key_vigenere.rejected.connect(self.plainTextEdit_key_vigenere.clear) # type: ignore
        self.buttonBoxSend_vigenere.rejected.connect(self.plainTextEdit_vigenere.clear) # type: ignore
        self.buttonBoxSend_vigenere.accepted.connect(self.plainTextEdit_vigenere.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "Choix du port"))
        self.pushButton_port.setText(_translate("MainWindow", "Envoyer"))
        self.pushButton_normal.setText(_translate("MainWindow", "Envoyer"))
        self.tabtool_encoding.setTabText(self.tabtool_encoding.indexOf(self.tab_normal), _translate("MainWindow", "Normal"))
        self.pushButton_shift.setText(_translate("MainWindow", "Envoyer"))
        self.pushButton_shift_key.setText(_translate("MainWindow", "Envoyer"))
        self.label_8.setText(_translate("MainWindow", "Shift"))
        self.pushButton_clear.setText(_translate("MainWindow", "Clear chat"))
        self.tabtool_encoding.setTabText(self.tabtool_encoding.indexOf(self.tab_shift), _translate("MainWindow", "Page"))
        self.label_2.setText(_translate("MainWindow", "Mot clé d\'encodage"))
        self.label_5.setText(_translate("MainWindow", "Vigenere"))
        self.tabtool_encoding.setTabText(self.tabtool_encoding.indexOf(self.tab_vigenere), _translate("MainWindow", "Vigenere"))
        self.PrivateKeyLabel.setText(_translate("MainWindow", "Private Key"))
        self.RSA_Key_button_generator.setText(_translate("MainWindow", "Generate RSA Key"))
        self.PublicKeyLabel.setText(_translate("MainWindow", "Public Key"))
        self.label_4.setText(_translate("MainWindow", "RSA"))
        self.tabtool_encoding.setTabText(self.tabtool_encoding.indexOf(self.tab_rsa), _translate("MainWindow", "RSA"))
        self.pushButton_5.setText(_translate("MainWindow", "Task Diffie-Hellman"))
        self.pushButton_4.setText(_translate("MainWindow", "Task RSA encode"))
        self.pushButton_9.setText(_translate("MainWindow", "Task Hash verify"))
        self.pushButton_3.setText(_translate("MainWindow", "Task RSA decode"))
        self.pushButton_8.setText(_translate("MainWindow", "Task Hash hash"))
        self.pushButton_6.setText(_translate("MainWindow", "Task Vigenere"))
        self.pushButton_7.setText(_translate("MainWindow", "Task Shift"))
        self.tabtool_encoding.setTabText(self.tabtool_encoding.indexOf(self.tab_DH), _translate("MainWindow", "Task"))
        self.label.setText(_translate("MainWindow", "Chat Serveur Live"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
