# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_crypto_V3.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(721, 378)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(True)
        self.windows_layout = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.windows_layout.sizePolicy().hasHeightForWidth())
        self.windows_layout.setSizePolicy(sizePolicy)
        self.windows_layout.setStyleSheet("/*-----QWidget-----*/\n"
"QWidget\n"
"{\n"
"    background-color: #121212;\n"
"    color: #ffffff;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLabel-----*/\n"
"QLabel\n"
"{\n"
"    background-color: transparent;\n"
"    color: #ffffff;\n"
"\n"
"}\n"
"\n"
"\n"
"QLabel::disabled\n"
"{\n"
"    background-color: transparent;\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QMenuBar-----*/\n"
"QMenuBar\n"
"{\n"
"    background-color: #0a0a0a;\n"
"    color: #ffffff;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item\n"
"{\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item:selected\n"
"{\n"
"    background-color: #607cff;\n"
"    border: 1px solid #41cd52;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item:pressed\n"
"{\n"
"    background-color: #4969ff;\n"
"    border: 1px solid #000;\n"
"    margin-bottom: -1px;\n"
"    padding-bottom: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QMenu-----*/\n"
"QMenu\n"
"{\n"
"    background-color: #121212;\n"
"    border: 1px solid;\n"
"    color: #ffffff;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::separator\n"
"{\n"
"    height: 1px;\n"
"    background-color: #6d8eff;\n"
"    color: #ffffff;\n"
"    padding-left: 4px;\n"
"    margin-left: 10px;\n"
"    margin-right: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item\n"
"{\n"
"    min-width : 150px;\n"
"    padding: 3px 20px 3px 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"    background-color: #4969ff;\n"
"    color: #ffffff;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item:disabled\n"
"{\n"
"    color: #262626;\n"
"}\n"
"\n"
"\n"
"/*-----QToolTip-----*/\n"
"QToolTip\n"
"{\n"
"    border : 1px solid #000000;\n"
"    background-color: #26264f;\n"
"    color: #ffffff;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"/*-----QPushButton-----*/\n"
"QPushButton\n"
"{\n"
"    background-color: #607cff;\n"
"    color: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    border-color: #051a39;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #8399ff;\n"
"    color: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    border-color: #051a39;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #4969ff;\n"
"    color: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    border-color: #051a39;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolButton-----*/\n"
"QToolButton\n"
"{\n"
"    background-color: #607cff;\n"
"    color: #ffffff;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    border-color: #051a39;\n"
"    padding: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolButton::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolButton::hover\n"
"{\n"
"    background-color: #8399ff;\n"
"    color: #ffffff;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    border-color: #051a39;\n"
"    padding: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolButton::pressed\n"
"{\n"
"    background-color: #4969ff;\n"
"    color: #ffffff;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    border-color: #051a39;\n"
"    padding: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QComboBox-----*/\n"
"QComboBox\n"
"{\n"
"    background-color: #607cff;\n"
"    border: 1px solid;\n"
"    border-radius: 3px;\n"
"    padding-left: 6px;\n"
"    color: #ffffff;\n"
"    height: 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox:hover\n"
"{\n"
"    background-color: #8399ff;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox:on\n"
"{\n"
"    background-color: #4969ff;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    background-color: #383838;\n"
"    color: #ffffff;\n"
"    border: 1px solid black;\n"
"    selection-background-color: #4969ff;\n"
"    selection-color: #ffffff;\n"
"    outline: 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox::drop-down\n"
"{\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    border-left-width: 0px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; \n"
"    border-top-right-radius: 3px; \n"
"    border-bottom-right-radius: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox::down-arrow\n"
"{\n"
"    image: url(://arrow-down.png);\n"
"    width: 8px;\n"
"    height: 8px;\n"
"}\n"
"\n"
"\n"
"/*-----QSpinBox & QDoubleSpinBox & QDateTimeEdit-----*/\n"
"QSpinBox, \n"
"QDoubleSpinBox,\n"
"QDateTimeEdit\n"
"{\n"
"    background-color: #525251;\n"
"    color: #ffffff;\n"
"    border: 1px solid #051a39;\n"
"    border-radius: 3px;\n"
"    padding : 2px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::disabled, \n"
"QDoubleSpinBox::disabled,\n"
"QDateTimeEdit::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox:hover, \n"
"QDoubleSpinBox::hover,\n"
"QDateTimeEdit::hover\n"
"{\n"
"    background-color: #626262;\n"
"    border: 1px solid #607cff;\n"
"    color:  #fff;\n"
"    padding: 2px\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-button, QSpinBox::down-button,\n"
"QDoubleSpinBox::up-button, QDoubleSpinBox::down-button,\n"
"QDateTimeEdit::up-button, QDateTimeEdit::down-button\n"
"{\n"
"    background-color: #607cff;\n"
"    border-radius: 2px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::disabled, \n"
"QDoubleSpinBox::disabled,\n"
"QDateTimeEdit::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-button:hover, QSpinBox::down-button:hover,\n"
"QDoubleSpinBox::up-button:hover, QDoubleSpinBox::down-button:hover,\n"
"QDateTimeEdit::up-button:hover, QDateTimeEdit::down-button:hover\n"
"{\n"
"    background-color: #8399ff;\n"
"    border: 1px solid #8399ff;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-button:disabled, QSpinBox::down-button:disabled,\n"
"QDoubleSpinBox::up-button:disabled, QDoubleSpinBox::down-button:disabled,\n"
"QDateTimeEdit::up-button:disabled, QDateTimeEdit::down-button:disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-button:pressed, QSpinBox::down-button:pressed,\n"
"QDoubleSpinBox::up-button:pressed, QDoubleSpinBox::down-button::pressed,\n"
"QDateTimeEdit::up-button:pressed, QDateTimeEdit::down-button::pressed\n"
"{\n"
"    background-color: #4969ff;\n"
"    border: 1px solid #4969ff;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::down-arrow,\n"
"QDoubleSpinBox::down-arrow,\n"
"QDateTimeEdit::down-arrow\n"
"{\n"
"    image: url(://arrow-down.png);\n"
"    width: 7px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-arrow,\n"
"QDoubleSpinBox::up-arrow,\n"
"QDateTimeEdit::up-arrow\n"
"{\n"
"    image: url(://arrow-up.png);\n"
"    width: 7px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLineEdit-----*/\n"
"QLineEdit\n"
"{\n"
"    background-color: #525251;\n"
"    color: #ffffff;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    border-color: #051a39;\n"
"    padding: 2px;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    border-color: #051a39;\n"
"    padding: 2px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QTextEdit-----*/\n"
"QTextEdit\n"
"{\n"
"    /* background-color: rgb(18, 18, 18); */\n"
"    color: #cecece;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QTextEdit::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QGroupBox-----*/\n"
"QGroupBox \n"
"{\n"
"    border: 1px solid;\n"
"    border-color: #607cff;\n"
"    margin-top: 22px;\n"
"\n"
"}\n"
"\n"
"\n"
"QGroupBox::title  \n"
"{\n"
"    background-color: #607cff;\n"
"    color: #ffffff;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 5px;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QGroupBox::title::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 5px;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QRadioButton-----*/\n"
"QRadioButton::indicator::unchecked\n"
"{ \n"
"    border: 2px inset gray; \n"
"    border-radius: 5px; \n"
"    background-color:  #fff;\n"
"    width: 9px; \n"
"    height: 9px; \n"
"\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::unchecked:hover\n"
"{ \n"
"    border: 2px solid #607cff; \n"
"    border-radius: 5px; \n"
"    background-color:  #fff;\n"
"    width: 9px; \n"
"    height: 9px; \n"
"\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::checked\n"
"{ \n"
"    border: 2px inset darkgray; \n"
"    border-radius: 5px; \n"
"    background-color: #4969ff; \n"
"    width: 9px; \n"
"    height: 9px; \n"
"\n"
"}\n"
"\n"
"\n"
"QRadioButton::disabled\n"
"{\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator:disabled\n"
"{\n"
"    background-color: #656565;\n"
"    color: #656565;\n"
"    border: 2px solid #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QTableView & QTableWidget-----*/\n"
"QTableView\n"
"{\n"
"    background-color: #242526;\n"
"    border: 1px solid #32414B;\n"
"    color: #f0f0f0;\n"
"    gridline-color: #8faaff;\n"
"    outline : 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableView::disabled\n"
"{\n"
"    background-color: #242526;\n"
"    border: 1px solid #32414B;\n"
"    color: #656565;\n"
"    gridline-color: #656565;\n"
"    outline : 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableView::item:hover \n"
"{\n"
"    background-color: #26264f;\n"
"    color: #f0f0f0;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableView::item:selected \n"
"{\n"
"    background-color: #1a1b1c;\n"
"    border: 2px solid #4969ff;\n"
"    color: #F0F0F0;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableView::item:selected:disabled\n"
"{\n"
"    background-color: #1a1b1c;\n"
"    border: 2px solid #525251;\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableCornerButton::section\n"
"{\n"
"    background-color: #505050;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section\n"
"{\n"
"    background-color: #525251;\n"
"    color: #fff;\n"
"    text-align: left;\n"
"    padding: 4px;\n"
"    \n"
"}\n"
"\n"
"\n"
"QHeaderView::section:disabled\n"
"{\n"
"    background-color: #525251;\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section:checked\n"
"{\n"
"    color: #fff;\n"
"    background-color: #4969ff;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section:checked:disabled\n"
"{\n"
"    color: #656565;\n"
"    background-color: #525251;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::vertical::first,\n"
"QHeaderView::section::vertical::only-one\n"
"{\n"
"    border-top: 1px solid #353635;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::vertical\n"
"{\n"
"    border-top: 1px solid #353635;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::horizontal::first,\n"
"QHeaderView::section::horizontal::only-one\n"
"{\n"
"    border-left: 1px solid #353635;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::horizontal\n"
"{\n"
"    border-left: 1px solid #353635;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QTabWidget-----*/\n"
"QTabBar::tab\n"
"{\n"
"    background-color: #262626;\n"
"    color: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    border-color: #051a39;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:disabled\n"
"{\n"
"    background-color: #656565;\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabWidget::pane \n"
"{\n"
"    background-color: #262626;\n"
"    color: #ffffff;\n"
"    border: 1px solid;\n"
"    border-color: #607cff;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:selected\n"
"{\n"
"    background-color: #607cff;\n"
"    color: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    border-color: #051a39;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:selected:disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:!selected \n"
"{\n"
"    background-color: #262626;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:!selected:hover \n"
"{\n"
"    background-color: #8399ff;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:top:!selected \n"
"{\n"
"    margin-top: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:bottom:!selected \n"
"{\n"
"    margin-bottom: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:top, QTabBar::tab:bottom \n"
"{\n"
"    min-width: 8ex;\n"
"    margin-right: -1px;\n"
"    padding: 5px 10px 5px 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:top:selected \n"
"{\n"
"    border-bottom-color: none;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:bottom:selected \n"
"{\n"
"    border-top-color: none;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:top:last, QTabBar::tab:bottom:last,\n"
"QTabBar::tab:top:only-one, QTabBar::tab:bottom:only-one \n"
"{\n"
"    margin-right: 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:left:!selected \n"
"{\n"
"    margin-right: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:right:!selected\n"
"{\n"
"    margin-left: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:left, QTabBar::tab:right \n"
"{\n"
"    min-height: 8ex;\n"
"    margin-bottom: -1px;\n"
"    padding: 10px 5px 10px 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:left:selected \n"
"{\n"
"    border-left-color: none;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:right:selected \n"
"{\n"
"    border-right-color: none;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:left:last, QTabBar::tab:right:last,\n"
"QTabBar::tab:left:only-one, QTabBar::tab:right:only-one \n"
"{\n"
"    margin-bottom: 0;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QSlider-----*/\n"
"QSlider::groove:horizontal \n"
"{\n"
"    background-color: transparent;\n"
"    height: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:horizontal \n"
"{\n"
"    background-color: #607cff;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::add-page:horizontal \n"
"{\n"
"    background-color: #666765;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:horizontal \n"
"{\n"
"    background-color: #607cff;\n"
"    width: 14px;\n"
"    margin-top: -6px;\n"
"    margin-bottom: -6px;\n"
"    border-radius: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:horizontal:hover \n"
"{\n"
"    background-color: #607cff;\n"
"    border-radius: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:horizontal:disabled \n"
"{\n"
"    background-color: #bbb;\n"
"    border-color: #999;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::add-page:horizontal:disabled \n"
"{\n"
"    background-color: #eee;\n"
"    border-color: #999;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:horizontal:disabled \n"
"{\n"
"    background-color: #eee;\n"
"    border: 1px solid #aaa;\n"
"    border-radius: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::groove:vertical \n"
"{\n"
"    background-color: transparent;\n"
"    width: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:vertical \n"
"{\n"
"    background-color: #607cff;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::add-page:vertical \n"
"{\n"
"    background-color: #666765;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:vertical \n"
"{\n"
"    background-color: #607cff;\n"
"    height: 14px;\n"
"    margin-left: -6px;\n"
"    margin-right: -6px;\n"
"    border-radius: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:vertical:hover \n"
"{\n"
"    background-color: #607cff;\n"
"    border-radius: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:vertical:disabled \n"
"{\n"
"    background-color: #bbb;\n"
"    border-color: #999;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::add-page:vertical:disabled \n"
"{\n"
"    background-color: #eee;\n"
"    border-color: #999;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:vertical:disabled \n"
"{\n"
"    background-color: #eee;\n"
"    border: 1px solid #aaa;\n"
"    border-radius: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QDial-----*/\n"
"QDial\n"
"{\n"
"    background-color: #607cff;\n"
"\n"
"}\n"
"\n"
"\n"
"QDial::disabled\n"
"{\n"
"    background-color: #404040;\n"
"\n"
"}\n"
"\n"
"/*-----QScrollBar-----*/\n"
"QScrollBar:horizontal\n"
"{\n"
"    border: 1px solid #222222;\n"
"    background-color: #3d3d3d;\n"
"    height: 13px;\n"
"    margin: 0px 16px 0 16px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:horizontal\n"
"{\n"
"    background: #607cff;\n"
"    min-height: 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal\n"
"{\n"
"    border: 1px solid #1b1b19;\n"
"    background-color: #607cff;\n"
"    width: 14px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:horizontal\n"
"{\n"
"    border: 1px solid #1b1b19;\n"
"    background-color: #607cff;\n"
"    width: 14px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::right-arrow:horizontal\n"
"{\n"
"    image: url(://arrow-right.png);\n"
"    width: 6px;\n"
"    height: 6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::left-arrow:horizontal\n"
"{\n"
"    image: url(://arrow-left.png);\n"
"    width: 6px;\n"
"    height: 6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"    background: none;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"    background-color: #3d3d3d;\n"
"    width: 13px;\n"
"    margin: 16px 0 16px 0;\n"
"    border: 1px solid #222222;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
"    background-color: #607cff;\n"
"    min-height: 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"    border: 1px solid #1b1b19;\n"
"    background-color: #607cff;\n"
"    height: 14px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"    border: 1px solid #1b1b19;\n"
"    background-color: #607cff;\n"
"    height: 14px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::up-arrow:vertical\n"
"{\n"
"    image: url(://arrow-up.png);\n"
"    width: 6px;\n"
"    height: 6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::down-arrow:vertical\n"
"{\n"
"    image: url(://arrow-down.png);\n"
"    width: 6px;\n"
"    height: 6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"    background: none;\n"
"\n"
"}\n"
"\n"
"/*-----QProgressBar-----*/\n"
"QProgressBar\n"
"{\n"
"    border: 1px solid #222222;\n"
"    background-color: #3d3d3d;\n"
"    text-align: center;\n"
"    color: #ffffff;\n"
"    font-size: 12px;\n"
"    /* font-weight: bold; */\n"
"    padding: 1px;\n"
"    border-radius: 3px;\n"
"}\n"
"QProgressBar::chunk\n"
"{\n"
"    background-color: #607cff;\n"
"}")
        self.windows_layout.setObjectName("windows_layout")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.windows_layout)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.main_layout = QtWidgets.QGridLayout()
        self.main_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.main_layout.setContentsMargins(-1, -1, 0, 0)
        self.main_layout.setObjectName("main_layout")
        self.line_3 = QtWidgets.QFrame(self.windows_layout)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.main_layout.addWidget(self.line_3, 2, 1, 1, 1)
        self.tab_layout = QtWidgets.QGridLayout()
        self.tab_layout.setObjectName("tab_layout")
        self.tabtool_encoding = QtWidgets.QTabWidget(self.windows_layout)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.tabtool_encoding.setFont(font)
        self.tabtool_encoding.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabtool_encoding.setMouseTracking(False)
        self.tabtool_encoding.setTabletTracking(False)
        self.tabtool_encoding.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabtool_encoding.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabtool_encoding.setIconSize(QtCore.QSize(20, 20))
        self.tabtool_encoding.setElideMode(QtCore.Qt.ElideNone)
        self.tabtool_encoding.setTabBarAutoHide(False)
        self.tabtool_encoding.setObjectName("tabtool_encoding")
        self.tab_normal = QtWidgets.QWidget()
        self.tab_normal.setObjectName("tab_normal")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_normal)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.plainTextEdit_normal = QtWidgets.QPlainTextEdit(self.tab_normal)
        self.plainTextEdit_normal.setMaximumSize(QtCore.QSize(9999999, 150))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.plainTextEdit_normal.setFont(font)
        self.plainTextEdit_normal.setObjectName("plainTextEdit_normal")
        self.gridLayout_3.addWidget(self.plainTextEdit_normal, 3, 0, 1, 2)
        self.textEdit_port = QtWidgets.QTextEdit(self.tab_normal)
        self.textEdit_port.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.textEdit_port.setFont(font)
        self.textEdit_port.setObjectName("textEdit_port")
        self.gridLayout_3.addWidget(self.textEdit_port, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_normal)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_7.setFont(font)
        self.label_7.setScaledContents(True)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 3)
        self.pushButton_port = QtWidgets.QPushButton(self.tab_normal)
        self.pushButton_port.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_port.setFont(font)
        self.pushButton_port.setObjectName("pushButton_port")
        self.gridLayout_3.addWidget(self.pushButton_port, 1, 1, 1, 1)
        self.pushButton_normal = QtWidgets.QPushButton(self.tab_normal)
        self.pushButton_normal.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_normal.setFont(font)
        self.pushButton_normal.setObjectName("pushButton_normal")
        self.gridLayout_3.addWidget(self.pushButton_normal, 3, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 2, 1, 1, 1)
        self.tabtool_encoding.addTab(self.tab_normal, "")
        self.tab_shift = QtWidgets.QWidget()
        self.tab_shift.setObjectName("tab_shift")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_shift)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.plainTextEdit_shift_key = QtWidgets.QPlainTextEdit(self.tab_shift)
        self.plainTextEdit_shift_key.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.plainTextEdit_shift_key.setFont(font)
        self.plainTextEdit_shift_key.setObjectName("plainTextEdit_shift_key")
        self.gridLayout_2.addWidget(self.plainTextEdit_shift_key, 2, 0, 1, 1)
        self.pushButton_shift_key = QtWidgets.QPushButton(self.tab_shift)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_shift_key.setFont(font)
        self.pushButton_shift_key.setObjectName("pushButton_shift_key")
        self.gridLayout_2.addWidget(self.pushButton_shift_key, 2, 1, 1, 1)
        self.plainTextEdit_shift = QtWidgets.QPlainTextEdit(self.tab_shift)
        self.plainTextEdit_shift.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.plainTextEdit_shift.setFont(font)
        self.plainTextEdit_shift.setObjectName("plainTextEdit_shift")
        self.gridLayout_2.addWidget(self.plainTextEdit_shift, 4, 0, 1, 3)
        self.pushButton_shift = QtWidgets.QPushButton(self.tab_shift)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_shift.setFont(font)
        self.pushButton_shift.setObjectName("pushButton_shift")
        self.gridLayout_2.addWidget(self.pushButton_shift, 4, 3, 1, 1)
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.tab_shift)
        self.lcdNumber_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.gridLayout_2.addWidget(self.lcdNumber_3, 2, 2, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 3, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_shift)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_8.setFont(font)
        self.label_8.setScaledContents(True)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        self.pushButton_clear = QtWidgets.QPushButton(self.tab_shift)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.gridLayout_2.addWidget(self.pushButton_clear, 0, 3, 1, 1)
        self.tabtool_encoding.addTab(self.tab_shift, "")
        self.tab_vigenere = QtWidgets.QWidget()
        self.tab_vigenere.setObjectName("tab_vigenere")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_vigenere)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_vigenere_key = QtWidgets.QPushButton(self.tab_vigenere)
        self.pushButton_vigenere_key.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_vigenere_key.setFont(font)
        self.pushButton_vigenere_key.setObjectName("pushButton_vigenere_key")
        self.gridLayout_4.addWidget(self.pushButton_vigenere_key, 3, 1, 1, 1)
        self.pushButton_vigenere = QtWidgets.QPushButton(self.tab_vigenere)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_vigenere.setFont(font)
        self.pushButton_vigenere.setObjectName("pushButton_vigenere")
        self.gridLayout_4.addWidget(self.pushButton_vigenere, 5, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_vigenere)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_10.setFont(font)
        self.label_10.setScaledContents(True)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 0, 1, 1, 1)
        self.pushButton_clear_2 = QtWidgets.QPushButton(self.tab_vigenere)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_clear_2.setFont(font)
        self.pushButton_clear_2.setObjectName("pushButton_clear_2")
        self.gridLayout_4.addWidget(self.pushButton_clear_2, 0, 3, 1, 1)
        self.plainTextEdit_vigenere_key = QtWidgets.QPlainTextEdit(self.tab_vigenere)
        self.plainTextEdit_vigenere_key.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.plainTextEdit_vigenere_key.setFont(font)
        self.plainTextEdit_vigenere_key.setObjectName("plainTextEdit_vigenere_key")
        self.gridLayout_4.addWidget(self.plainTextEdit_vigenere_key, 3, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_vigenere)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_9.setFont(font)
        self.label_9.setScaledContents(True)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 2, 0, 1, 4)
        self.textBrowser_vigenere_key = QtWidgets.QTextBrowser(self.tab_vigenere)
        self.textBrowser_vigenere_key.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.textBrowser_vigenere_key.setFont(font)
        self.textBrowser_vigenere_key.setObjectName("textBrowser_vigenere_key")
        self.gridLayout_4.addWidget(self.textBrowser_vigenere_key, 3, 2, 1, 2)
        self.plainTextEdit_vigenere = QtWidgets.QPlainTextEdit(self.tab_vigenere)
        self.plainTextEdit_vigenere.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.plainTextEdit_vigenere.setFont(font)
        self.plainTextEdit_vigenere.setObjectName("plainTextEdit_vigenere")
        self.gridLayout_4.addWidget(self.plainTextEdit_vigenere, 5, 0, 1, 3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem4, 4, 0, 1, 1)
        self.tabtool_encoding.addTab(self.tab_vigenere, "")
        self.tab_task = QtWidgets.QWidget()
        self.tab_task.setObjectName("tab_task")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_task)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton_hash_verify_task = QtWidgets.QPushButton(self.tab_task)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_hash_verify_task.setFont(font)
        self.pushButton_hash_verify_task.setObjectName("pushButton_hash_verify_task")
        self.gridLayout_6.addWidget(self.pushButton_hash_verify_task, 3, 2, 1, 1)
        self.pushButton_shift_task = QtWidgets.QPushButton(self.tab_task)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_shift_task.setFont(font)
        self.pushButton_shift_task.setObjectName("pushButton_shift_task")
        self.gridLayout_6.addWidget(self.pushButton_shift_task, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.chatTask = QtWidgets.QTextBrowser(self.tab_task)
        self.chatTask.setMaximumSize(QtCore.QSize(16777215, 400))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.chatTask.setFont(font)
        self.chatTask.setObjectName("chatTask")
        self.gridLayout.addWidget(self.chatTask, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout, 5, 0, 1, 3)
        self.label_11 = QtWidgets.QLabel(self.tab_task)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_11.setFont(font)
        self.label_11.setScaledContents(True)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem5, 4, 1, 1, 1)
        self.pushButton_dh_task = QtWidgets.QPushButton(self.tab_task)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_dh_task.setFont(font)
        self.pushButton_dh_task.setObjectName("pushButton_dh_task")
        self.gridLayout_6.addWidget(self.pushButton_dh_task, 3, 0, 1, 1)
        self.pushButton_RSA_encode_task = QtWidgets.QPushButton(self.tab_task)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_RSA_encode_task.setFont(font)
        self.pushButton_RSA_encode_task.setObjectName("pushButton_RSA_encode_task")
        self.gridLayout_6.addWidget(self.pushButton_RSA_encode_task, 2, 2, 1, 1)
        self.pushButton_hash_hash_task = QtWidgets.QPushButton(self.tab_task)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_hash_hash_task.setFont(font)
        self.pushButton_hash_hash_task.setObjectName("pushButton_hash_hash_task")
        self.gridLayout_6.addWidget(self.pushButton_hash_hash_task, 3, 1, 1, 1)
        self.pushButton_vigenere_task = QtWidgets.QPushButton(self.tab_task)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_vigenere_task.setFont(font)
        self.pushButton_vigenere_task.setObjectName("pushButton_vigenere_task")
        self.gridLayout_6.addWidget(self.pushButton_vigenere_task, 2, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem6, 1, 1, 1, 1)
        self.tabtool_encoding.addTab(self.tab_task, "")
        self.tab_layout.addWidget(self.tabtool_encoding, 0, 0, 1, 1)
        self.main_layout.addLayout(self.tab_layout, 2, 0, 1, 1)
        self.chat_layout = QtWidgets.QVBoxLayout()
        self.chat_layout.setObjectName("chat_layout")
        self.label = QtWidgets.QLabel(self.windows_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.chat_layout.addWidget(self.label)
        self.line_2 = QtWidgets.QFrame(self.windows_layout)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.chat_layout.addWidget(self.line_2)
        self.ChatDisplay = QtWidgets.QTextBrowser(self.windows_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ChatDisplay.sizePolicy().hasHeightForWidth())
        self.ChatDisplay.setSizePolicy(sizePolicy)
        self.ChatDisplay.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ChatDisplay.setFont(font)
        self.ChatDisplay.setObjectName("ChatDisplay")
        self.chat_layout.addWidget(self.ChatDisplay)
        self.main_layout.addLayout(self.chat_layout, 0, 2, 3, 1)
        self.gridLayout_5.addLayout(self.main_layout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.windows_layout)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 721, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabtool_encoding.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "Choix du port"))
        self.pushButton_port.setText(_translate("MainWindow", "Envoyer"))
        self.pushButton_normal.setText(_translate("MainWindow", "Envoyer"))
        self.tabtool_encoding.setTabText(self.tabtool_encoding.indexOf(self.tab_normal), _translate("MainWindow", "Normal"))
        self.pushButton_shift_key.setText(_translate("MainWindow", "Envoyer"))
        self.pushButton_shift.setText(_translate("MainWindow", "Envoyer"))
        self.label_8.setText(_translate("MainWindow", "Shift"))
        self.pushButton_clear.setText(_translate("MainWindow", "Clear chat"))
        self.tabtool_encoding.setTabText(self.tabtool_encoding.indexOf(self.tab_shift), _translate("MainWindow", "Shift"))
        self.pushButton_vigenere_key.setText(_translate("MainWindow", "Envoyer"))
        self.pushButton_vigenere.setText(_translate("MainWindow", "Envoyer"))
        self.label_10.setText(_translate("MainWindow", "Vigenere"))
        self.pushButton_clear_2.setText(_translate("MainWindow", "Clear chat"))
        self.label_9.setText(_translate("MainWindow", "Mot clé"))
        self.tabtool_encoding.setTabText(self.tabtool_encoding.indexOf(self.tab_vigenere), _translate("MainWindow", "Vigenere"))
        self.pushButton_hash_verify_task.setText(_translate("MainWindow", "Hash verify"))
        self.pushButton_shift_task.setText(_translate("MainWindow", "Shift"))
        self.label_11.setText(_translate("MainWindow", "Task"))
        self.pushButton_dh_task.setText(_translate("MainWindow", "Diffie Hellman"))
        self.pushButton_RSA_encode_task.setText(_translate("MainWindow", "RSA encode"))
        self.pushButton_hash_hash_task.setText(_translate("MainWindow", "Hash hash"))
        self.pushButton_vigenere_task.setText(_translate("MainWindow", "Vigenere"))
        self.tabtool_encoding.setTabText(self.tabtool_encoding.indexOf(self.tab_task), _translate("MainWindow", "Task"))
        self.label.setText(_translate("MainWindow", "Chat Serveur Live"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
